#
#	server.markhome.mcf.CFSec
#
#	Copyright (c) 2016-2026 Mark Stephen Sobkow
#	
#	Mark's Code Fractal 3.1 CFSec - Security Services
#	
#	Copyright (c) 2016-2026 Mark Stephen Sobkow mark.sobkow@gmail.com
#	
#	These files are part of Mark's Code Fractal CFSec.
#	
#	Licensed under the Apache License, Version 2.0 (the "License");
#	you may not use this file except in compliance with the License.
#	You may obtain a copy of the License at
#	
#	http://www.apache.org/licenses/LICENSE-2.0
#	
#	Unless required by applicable law or agreed to in writing, software
#	distributed under the License is distributed on an "AS IS" BASIS,
#	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#	See the License for the specific language governing permissions and
#	limitations under the License.
#	
#
cfsec.javafx.Cluster.AttrPane.Id.EffLabel=Id
cfsec.javafx.Cluster.AttrPane.FullDomName.EffLabel=Full Domain Name
cfsec.javafx.Cluster.AttrPane.Description.EffLabel=Cluster Description
cfsec.javafx.Tenant.AttrPane.Id.EffLabel=Id
cfsec.javafx.Tenant.AttrPane.TenantName.EffLabel=TenantName
cfsec.javafx.Tenant.AttrPane.ContainerCluster.EffLabel=Cluster
cfsec.javafx.TableInfo.AttrPane.TableInfoId.EffLabel=TableInfoId
cfsec.javafx.TableInfo.AttrPane.SchemaName.EffLabel=SchemaName
cfsec.javafx.TableInfo.AttrPane.TableName.EffLabel=TableName
cfsec.javafx.TableInfo.AttrPane.BackingClassCode.EffLabel=BackingClassCode
cfsec.javafx.TableInfo.AttrPane.RuntimeClassCode.EffLabel=RuntimeClassCode
cfsec.javafx.TableInfo.AttrPane.HasHistory.EffLabel=HasHistory
cfsec.javafx.TableInfo.AttrPane.IsMutable.EffLabel=IsMutable
cfsec.javafx.TableInfo.AttrPane.SecScopeName.EffLabel=SecScopeName
cfsec.javafx.TableInfo.AttrPane.CodeVis.EffLabel=CodeVis
cfsec.javafx.ISOCcy.AttrPane.ISOCcyId.EffLabel=ISOCcyId
cfsec.javafx.ISOCcy.AttrPane.ISOCode.EffLabel=ISOCode
cfsec.javafx.ISOCcy.AttrPane.Name.EffLabel=Name
cfsec.javafx.ISOCcy.AttrPane.UnitSymbol.EffLabel=UnitSymbol
cfsec.javafx.ISOCcy.AttrPane.Precis.EffLabel=Precis
cfsec.javafx.ISOCcy.AttrPane.ChildrenCtry.EffLabel=Ctry
cfsec.javafx.ISOCtry.AttrPane.ISOCtryId.EffLabel=ISOCtryId
cfsec.javafx.ISOCtry.AttrPane.ISOCode.EffLabel=ISOCode
cfsec.javafx.ISOCtry.AttrPane.Name.EffLabel=Name
cfsec.javafx.ISOCtryCcy.AttrPane.ContainerCtry.EffLabel=Ctry
cfsec.javafx.ISOCtryCcy.AttrPane.ParentCcy.EffLabel=Ccy
cfsec.javafx.ISOCtryLang.AttrPane.ContainerCtry.EffLabel=Ctry
cfsec.javafx.ISOCtryLang.AttrPane.ParentLang.EffLabel=Lang
cfsec.javafx.ISOLang.AttrPane.ISOLangId.EffLabel=ISOLangId
cfsec.javafx.ISOLang.AttrPane.ISO6392Code.EffLabel=ISO6392Code
cfsec.javafx.ISOLang.AttrPane.ISO6391Code.EffLabel=ISO6391Code
cfsec.javafx.ISOLang.AttrPane.EnglishName.EffLabel=EnglishName
cfsec.javafx.ISOLang.AttrPane.ChildrenCtry.EffLabel=Ctry
cfsec.javafx.ISOTZone.AttrPane.ISOTZoneId.EffLabel=ISO Timezone Id
cfsec.javafx.ISOTZone.AttrPane.Iso8601.EffLabel=ISO8601
cfsec.javafx.ISOTZone.AttrPane.TZName.EffLabel=Timezone Name
cfsec.javafx.ISOTZone.AttrPane.TZHourOffset.EffLabel=Timezone Hour Offset
cfsec.javafx.ISOTZone.AttrPane.TZMinOffset.EffLabel=Timezone Minute Offset
cfsec.javafx.ISOTZone.AttrPane.Description.EffLabel=Description
cfsec.javafx.ISOTZone.AttrPane.Visible.EffLabel=Visible
cfsec.javafx.SecUser.AttrPane.SecUserId.EffLabel=Security User Id
cfsec.javafx.SecUser.AttrPane.LoginId.EffLabel=Login Id
cfsec.javafx.SecUser.AttrPane.AccountStatus.EffLabel=Account Status
cfsec.javafx.SecUser.AttrPane.DfltSysGrpName.EffLabel=Default System Group Name
cfsec.javafx.SecUser.AttrPane.DfltClusGrpName.EffLabel=Default Cluster Group Name
cfsec.javafx.SecUser.AttrPane.DfltTentGrpName.EffLabel=Default Tenant Group Name
cfsec.javafx.SecUser.AttrPane.EMailAddress.EffLabel=EMail Address
cfsec.javafx.SecUser.AttrPane.ChildrenSysSecGrpMemb.EffLabel=System Security Group Members
cfsec.javafx.SecUser.AttrPane.ChildrenClusSecGrpMemb.EffLabel=Cluster Security Group Members
cfsec.javafx.SecUser.AttrPane.ChildrenTentSecGrpMemb.EffLabel=Tenant Security Group Members
cfsec.javafx.SecUserPassword.AttrPane.PWSetStamp.EffLabel=Password set at
cfsec.javafx.SecUserPassword.AttrPane.PasswordHash.EffLabel=Password Hash
cfsec.javafx.SecUserPassword.AttrPane.ContainerUser.EffLabel=Password For User
cfsec.javafx.SecUserEMConf.AttrPane.ConfirmEMailAddr.EffLabel=Confirm EMail Address
cfsec.javafx.SecUserEMConf.AttrPane.EMailSentStamp.EffLabel=Confirmation EMail Sent At
cfsec.javafx.SecUserEMConf.AttrPane.EMConfirmationUuid6.EffLabel=EMail Confirmation UUID6
cfsec.javafx.SecUserEMConf.AttrPane.NewAccount.EffLabel=Confirmation email is for new account?
cfsec.javafx.SecUserEMConf.AttrPane.ContainerUser.EffLabel=EMail Confirmation For User
cfsec.javafx.SecUserPWReset.AttrPane.SentToEMailAddr.EffLabel=Sent To EMail Address
cfsec.javafx.SecUserPWReset.AttrPane.PasswordResetUuid6.EffLabel=Password Reset UUID6
cfsec.javafx.SecUserPWReset.AttrPane.NewAccount.EffLabel=Password reset is for new account?
cfsec.javafx.SecUserPWReset.AttrPane.ContainerUser.EffLabel=Password Reset Request For User
cfsec.javafx.SecUserPWHistory.AttrPane.SecUserId.EffLabel=Security User Id
cfsec.javafx.SecUserPWHistory.AttrPane.PWSetStamp.EffLabel=Password set at
cfsec.javafx.SecUserPWHistory.AttrPane.PWReplacedStamp.EffLabel=Password set at
cfsec.javafx.SecUserPWHistory.AttrPane.PasswordHash.EffLabel=Password Hash
cfsec.javafx.SecSysGrp.AttrPane.SecSysGrpId.EffLabel=System Security Group Id
cfsec.javafx.SecSysGrp.AttrPane.Name.EffLabel=Name
cfsec.javafx.SecSysGrp.AttrPane.SecLevel.EffLabel=Group Level
cfsec.javafx.SecSysGrp.AttrPane.ChildrenMembByGrp.EffLabel=Members of Group
cfsec.javafx.SecSysGrp.AttrPane.ChildrenSysGrpByName.EffLabel=SysGroup by Name
cfsec.javafx.SecSysGrp.AttrPane.ChildrenRoleByEnableName.EffLabel=System Role by Name
cfsec.javafx.SecSysGrpInc.AttrPane.ContainerGroup.EffLabel=Group
cfsec.javafx.SecSysGrpInc.AttrPane.ParentSubGroup.EffLabel=SubGroup
cfsec.javafx.SecSysGrpMemb.AttrPane.ContainerGroup.EffLabel=Group
cfsec.javafx.SecSysGrpMemb.AttrPane.ParentUser.EffLabel=User
cfsec.javafx.SecClusGrp.AttrPane.SecClusGrpId.EffLabel=Cluster Security Group Id
cfsec.javafx.SecClusGrp.AttrPane.ContainerSysGrp.EffLabel=Reference system group
cfsec.javafx.SecClusGrp.AttrPane.ChildrenMembByGrp.EffLabel=Members of Group
cfsec.javafx.SecClusGrpMemb.AttrPane.ContainerGroup.EffLabel=Group
cfsec.javafx.SecClusGrpMemb.AttrPane.ParentUser.EffLabel=User
cfsec.javafx.SecTentGrp.AttrPane.SecTentGrpId.EffLabel=Tenant Security Group Id
cfsec.javafx.SecTentGrp.AttrPane.ContainerSysGrp.EffLabel=Reference system group
cfsec.javafx.SecTentGrp.AttrPane.ChildrenMembByGrp.EffLabel=Members of Group
cfsec.javafx.SecTentGrpMemb.AttrPane.ContainerGroup.EffLabel=Group
cfsec.javafx.SecTentGrpMemb.AttrPane.ParentUser.EffLabel=User
cfsec.javafx.SecSysRole.AttrPane.SecSysRoleId.EffLabel=Security System Role Id
cfsec.javafx.SecSysRole.AttrPane.Name.EffLabel=Name
cfsec.javafx.SecSysRole.AttrPane.ChildrenMembByRole.EffLabel=Members of System Role
cfsec.javafx.SecSysRoleEnables.AttrPane.ContainerSysRole.EffLabel=SysRole
cfsec.javafx.SecSysRoleEnables.AttrPane.ParentEnableGroup.EffLabel=Enable Group
cfsec.javafx.SecSysRoleMemb.AttrPane.ContainerSysRole.EffLabel=System Role
cfsec.javafx.SecSysRoleMemb.AttrPane.ParentUser.EffLabel=User
cfsec.javafx.SecClusRole.AttrPane.SecClusRoleId.EffLabel=Cluster Security Role Id
cfsec.javafx.SecClusRole.AttrPane.ContainerSysRole.EffLabel=System Role
cfsec.javafx.SecClusRole.AttrPane.ChildrenMembByGrp.EffLabel=Members of Group
cfsec.javafx.SecClusRoleMemb.AttrPane.ContainerRole.EffLabel=Role
cfsec.javafx.SecClusRoleMemb.AttrPane.ParentUser.EffLabel=User
cfsec.javafx.SecTentRole.AttrPane.SecTentRoleId.EffLabel=Tenant Security Role Id
cfsec.javafx.SecTentRole.AttrPane.ContainerSysRole.EffLabel=System Role
cfsec.javafx.SecTentRole.AttrPane.ChildrenMembByRole.EffLabel=Members of Role
cfsec.javafx.SecTentRoleMemb.AttrPane.ContainerRole.EffLabel=Role
cfsec.javafx.SecTentRoleMemb.AttrPane.ParentUser.EffLabel=User
cfsec.javafx.SecSession.AttrPane.SecSessionId.EffLabel=Security Session Id
cfsec.javafx.SecSession.AttrPane.SecUserId.EffLabel=Security User Id
cfsec.javafx.SecSession.AttrPane.Start.EffLabel=Start
cfsec.javafx.SecSession.AttrPane.Finish.EffLabel=Finish
cfsec.javafx.SecSession.AttrPane.SecProxyId.EffLabel=Security Proxy User Id
cfsec.javafx.SysCluster.AttrPane.SingletonId.EffLabel=Singleton
cfsec.javafx.SysCluster.AttrPane.ContainerCluster.EffLabel=Cluster
